# Generated by Django 4.1.1 on 2022-10-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Carusel adi')),
                ('title', models.CharField(max_length=50, verbose_name='Məhsulun adı')),
                ('content', models.TextField(blank=True, verbose_name='Yenilikler haqqinda')),
                ('image', models.ImageField(blank=True, upload_to='carusel_image/%Y/%m/%d/', verbose_name='Carusel Səkil')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Qiyməti AZN')),
                ('creded_at', models.DateTimeField(auto_now_add=True, verbose_name='Qeyd tarixi')),
            ],
            options={
                'verbose_name': 'Carusel',
                'verbose_name_plural': 'Carusel haqda',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Katiqoriya')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(upload_to='imagecat/%Y/%m/%d/', verbose_name='KatSəkil')),
            ],
            options={
                'verbose_name': 'Katiqoriya',
                'verbose_name_plural': 'Katiqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adi')),
                ('message', models.TextField(verbose_name='Mesajiniz')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('date_at', models.DateTimeField(auto_now_add=True, verbose_name='Qeyd tarixi')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefon nomresi')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Mektublar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Məhsulun adı')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/', verbose_name='Səkil')),
                ('probe', models.IntegerField(blank=True, null=True, verbose_name='Probu')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Çəkisi')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Qiyməti AZN')),
                ('creded_at', models.DateTimeField(auto_now_add=True, verbose_name='Qeyd tarixi')),
                ('creded_up', models.DateTimeField(auto_now=True, verbose_name='Yenilenme tarixi')),
                ('public', models.BooleanField(default=True, verbose_name='Dərc edilib')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='Email')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goldhome.category', verbose_name='Katiqoriya')),
                ('tags', models.ManyToManyField(blank=True, to='goldhome.tag', verbose_name='Secim novu')),
            ],
            options={
                'verbose_name': 'Qizil',
                'verbose_name_plural': 'Qizillar',
                'ordering': ['-creded_at'],
            },
        ),
    ]
