# Generated by Django 4.1.1 on 2022-10-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carusel',
            options={'ordering': ['-creded_at'], 'verbose_name': 'Carusel', 'verbose_name_plural': 'Carusel haqda'},
        ),
        migrations.AddField(
            model_name='carusel',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Dərc edilib'),
        ),
    ]
