# Generated by Django 4.1.1 on 2022-10-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldhome', '0002_alter_carusel_options_carusel_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Novu'),
        ),
    ]
