# Generated by Django 4.1.1 on 2022-10-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldhome', '0003_category_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='post_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Novu'),
        ),
    ]
