# Generated by Django 4.1.1 on 2022-10-26 13:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('goldhome', '0005_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='AZ', verbose_name='Telefon nomreniz'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='AZ', verbose_name='Telefon nomreniz'),
        ),
    ]
