# Generated by Django 4.1.1 on 2022-10-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldhome', '0006_alter_contact_phone_alter_phone_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Nov', 'verbose_name_plural': 'Novler'},
        ),
        migrations.AlterField(
            model_name='gold',
            name='post_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Modeli'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Adlari'),
        ),
    ]
